---
title: "World Cup History"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(rvest)
library(tidyverse)
library(ddplot)
library(data.table)
library(gapminder)
library(lubridate)
```

```{r}
wc <- read_csv("FIFA - World Cup Summary.csv")
att <- read_csv("FIFA World Cup Attendance.csv")

view(wc)

wc$CHAMPION <- gsub("West Germany", "Germany", wc$CHAMPION)
wc$`RUNNER UP` <- gsub("West Germany", "Germany", wc$`RUNNER UP`)
```

Column {data-width=500}
-----------------------------------------------------------------------

### World Cup Chart Race

```{r}
trophy <- data.table(year = c(1930, 1934, 1938, 1950, 1954,
                              1958, 1962, 1966, 1970, 1974,
                              1978, 1982, 1986, 1990, 1994,
                              1998, 2002, 2006, 2010, 2014,
                              2018, 2022),  
                     Uruguay = c(1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2),
                     Italy = c(0,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4),
                     Germany = c(0,0,0,0,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,4,4,4),
                     Brazil = c(0,0,0,0,0,1,2,2,3,3,3,3,3,3,4,4,5,5,5,5,5,5),
                     England = c(0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1),
                     Argentina = c(0,0,0,0,0,0,0,0,0,0,1,1,2,2,2,2,2,2,2,2,2,3),
                     France = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,2,2),
                     Spain = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1))

trophy <- pivot_longer(trophy, 2:9, names_to = "Campeão", values_to = "Quantidade")

trophy %>% 
  barChartRace(
    x = "Quantidade", 
    y = "Campeão",
    time = "year",
    title = "World Cup Champions through the Years",
    frameDur = 1000
  )
```

### Overall attendance through the Years

```{r}
avg_att <- ggplot(att) +
  aes(x = Year, y = Average_Attendance, fill = Year) +
  geom_col() +
  theme(legend.position="none")

ggplotly(avg_att)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Trophies Won

```{r}
p1 <- ggplot(wc) +
  aes(x = CHAMPION, fill = CHAMPION) + 
  geom_bar() +
  theme(legend.position="none")
ggplotly(p1)
```

### Runners-up

```{r}
p2 <- ggplot(wc) +
  aes(x = `RUNNER UP`, fill = `RUNNER UP`) +
  geom_bar() +
  theme(legend.position="none")
ggplotly(p2)
```

### Average goals per year

```{r}
avg_goals <- ggplot(wc) +
  aes(x = YEAR, y = `AVG GOALS PER GAME`) +
  geom_line() +
  theme(legend.position="none")
ggplotly(avg_goals)
```

